spring:
 profiles:
  active:
  - dev

---
spring:
 profiles: dev
 application:
   name: microservicecloud-config-hxr-dev
   
---
spring:
 profiles: test
 application:
   name: microservicecloud-config-hxr-test
   
   
